configured_endpoints: 19
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-ik2go9%2Fpetstore-fix-b0634ed005ad179d1b90206a3d1aef73327c6acd434ffd0e3954ecfeacfe7fb4.yml
