configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-ik2go9%2Fpetstore-fix-5b87b172ac4f0f46c515c73ed5affcf49d3b5bbc815a645600fb5a5c05edf79a.yml
